package com.greendao.DaoGen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.greendao.DaoGen.Job;
import com.greendao.DaoGen.Contact;

import com.greendao.DaoGen.JobDao;
import com.greendao.DaoGen.ContactDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig jobDaoConfig;
    private final DaoConfig contactDaoConfig;

    private final JobDao jobDao;
    private final ContactDao contactDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        jobDaoConfig = daoConfigMap.get(JobDao.class).clone();
        jobDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        jobDao = new JobDao(jobDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);

        registerDao(Job.class, jobDao);
        registerDao(Contact.class, contactDao);
    }
    
    public void clear() {
        jobDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
    }

    public JobDao getJobDao() {
        return jobDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

}
