package DaoGen.com.greendao.DaoGen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACT_ENTITY".
 */
public class ContactEntity {

    private Long id;
    private String number;
    private long contactId;

    public ContactEntity() {
    }

    public ContactEntity(Long id) {
        this.id = id;
    }

    public ContactEntity(Long id, String number, long contactId) {
        this.id = id;
        this.number = number;
        this.contactId = contactId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public long getContactId() {
        return contactId;
    }

    public void setContactId(long contactId) {
        this.contactId = contactId;
    }

}
