package DaoGen.com.greendao.DaoGen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import DaoGen.com.greendao.DaoGen.JobEntity;
import DaoGen.com.greendao.DaoGen.ContactEntity;

import DaoGen.com.greendao.DaoGen.JobEntityDao;
import DaoGen.com.greendao.DaoGen.ContactEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig jobEntityDaoConfig;
    private final DaoConfig contactEntityDaoConfig;

    private final JobEntityDao jobEntityDao;
    private final ContactEntityDao contactEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        jobEntityDaoConfig = daoConfigMap.get(JobEntityDao.class).clone();
        jobEntityDaoConfig.initIdentityScope(type);

        contactEntityDaoConfig = daoConfigMap.get(ContactEntityDao.class).clone();
        contactEntityDaoConfig.initIdentityScope(type);

        jobEntityDao = new JobEntityDao(jobEntityDaoConfig, this);
        contactEntityDao = new ContactEntityDao(contactEntityDaoConfig, this);

        registerDao(JobEntity.class, jobEntityDao);
        registerDao(ContactEntity.class, contactEntityDao);
    }
    
    public void clear() {
        jobEntityDaoConfig.getIdentityScope().clear();
        contactEntityDaoConfig.getIdentityScope().clear();
    }

    public JobEntityDao getJobEntityDao() {
        return jobEntityDao;
    }

    public ContactEntityDao getContactEntityDao() {
        return contactEntityDao;
    }

}
